base for framework done, apitests added
elza-99/Trello pull request #1
Opened 2021-11-09 14:15 UTC by elza-99

2021-11-09 14:51 UTC, GrebNat requested changes

2021-11-09 14:51 UTC, GrebNat commented on src/main/java/api/service/TrelloService.java
> +        return ConfigProperties.getProperty(API_KEY);
бал комент про проперти

getApiKey()...

2021-11-09 14:51 UTC, GrebNat commented on src/main/java/api/service/TrelloService.java
> +    public String getToken() {
эти методы нужно убрать в ConfigProperties, чтобы ими могли пользоваться все

2021-11-09 14:51 UTC, GrebNat commented on src/main/java/utils/ConfigProperties.java
> +    private static final String PATH = "src/test/resources/config.properties";
а где сам файлик config.properties? почему не закомичен?

2021-11-10 05:53 UTC, elza-99 commented on src/main/java/api/service/TrelloService.java
> +        return ConfigProperties.getProperty(API_KEY);
done, the method moved to ConfigProperties

2021-11-10 05:54 UTC, elza-99 commented on src/main/java/api/service/TrelloService.java
> +    public String getToken() {
done

2021-11-10 05:54 UTC, elza-99 commented on src/main/java/utils/ConfigProperties.java
> +    private static final String PATH = "src/test/resources/config.properties";
теперь закоммичен частично

2021-11-10 10:12 UTC, GrebNat approved these changes

2021-11-10 10:45 UTC, merged