ui tests added
elza-99/Trello pull request #2
Opened 2021-11-12 15:25 UTC by elza-99

2021-11-15 11:46 UTC, elza-99 commented
[index.html.zip](https://github.com/elza-99/Trello/files/7538406/index.html.zip)

2021-11-15 13:20 UTC, elza-99 commented
[index.html.zip](https://github.com/elza-99/Trello/files/7538925/index.html.zip)

2021-11-17 06:42 UTC, GrebNat requested changes

2021-11-17 06:42 UTC, GrebNat commented on src/main/java/ui/actions/BoardsActionsBuilder.java
> +    public BoardsPage build() {
зачем тут build()?
если мы говорим о паттерне флюент, то там нет никакого билда

2021-11-17 06:42 UTC, GrebNat commented on src/main/java/ui/actions/LoginActions.java
> +                .implicitlyWait(40, TimeUnit.SECONDS);
что тут происходит?

2021-11-17 06:42 UTC, GrebNat commented on src/main/java/ui/actions/LoginPageBuilder.java
> +    public LoginPage build() {
аналогичный вопрос, как с бордой

2021-11-17 06:42 UTC, GrebNat commented on src/main/java/ui/assertions/BoardsApiAssertions.java
> +    @Step
тоже можно добавить описание в аннотацию

2021-11-17 06:42 UTC, GrebNat commented on src/test/java/ui/BaseUITest.java
> +    @BeforeMethod(alwaysRun = true)
получается, что ты перед каждым тестом выполняешь все эти действия. 
иницивлизируй один раз, перед всеми тестами

2021-11-17 06:42 UTC, GrebNat commented on src/main/java/ui/assertions/BoardsUIAssertions.java
> +        boardsPage = new BoardsPage(driver);
давай не создавать борду, а использовать имеющуюся.
можно просто передавать ее сюда как паремтр, а можно в тесте использовать паттерн медиатор.
и , например это бы выглеело из тестка как

boardPage.createBoard(...).**checkThat().** assertThatBoardContainsCreatedList(listName)

2021-11-17 06:42 UTC, GrebNat commented on src/main/java/ui/assertions/HeaderMenuAssertions.java
> +        headerMenu = new HeaderMenu(driver);
аналогично про создание, как в борде

2021-11-17 06:42 UTC, GrebNat commented on src/main/java/ui/assertions/WorkspacesAssertions.java
> +        workspaces = new Workspaces(driver);
аналогично про НЕ создание, как в борде

2021-11-17 06:42 UTC, GrebNat commented on src/main/java/ui/components/HeaderMenu.java
> +    @FindBy(className = "_2ft40Nx3NZII2i")
такой локатор похож на кто-то вообще рандомное.
не думаю, что он сильно надежный

2021-11-17 06:42 UTC, GrebNat commented on src/main/java/ui/components/Workspaces.java
> +        for (WebElement e : boards) {
переделай на стримы

2021-11-17 06:42 UTC, GrebNat commented on src/main/java/ui/components/Workspaces.java
> +        driver.manage().timeouts().implicitlyWait(40, TimeUnit.SECONDS);
40 - это что-то незвестное. 
вообще часто встречается у тебя эт 40. не лучше бы вынести его в проперти?

2021-11-17 06:42 UTC, GrebNat commented on src/main/java/ui/pageobjects/BoardsPage.java
> +    public void addNewList() {
тут тоже везде переведи на флюет паттерн

2021-11-17 06:42 UTC, GrebNat commented on src/main/java/ui/pageobjects/HomePage.java
> +        this.headerMenu = new HeaderMenu(driver);
это уже в кончтрукторе абстракт станицы создается

2021-11-17 13:04 UTC, elza-99 commented on src/main/java/ui/actions/BoardsActionsBuilder.java
> +    public BoardsPage build() {
build удалён

2021-11-17 13:05 UTC, elza-99 commented on src/main/java/ui/actions/LoginActions.java
> +                .implicitlyWait(40, TimeUnit.SECONDS);
build удален, 40 перенесено в переменную

2021-11-17 13:05 UTC, elza-99 commented on src/main/java/ui/actions/LoginPageBuilder.java
> +    public LoginPage build() {
удалено

2021-11-17 13:05 UTC, elza-99 commented on src/main/java/ui/assertions/BoardsApiAssertions.java
> +    @Step
добавлено

2021-11-17 13:06 UTC, elza-99 commented on src/test/java/ui/BaseUITest.java
> +    @BeforeMethod(alwaysRun = true)
перенесла в @BeforeClass

2021-11-17 13:06 UTC, elza-99 commented on src/main/java/ui/components/HeaderMenu.java
> +    @FindBy(className = "_2ft40Nx3NZII2i")
локатор удалила - он больше не используется

2021-11-17 13:06 UTC, elza-99 commented on src/main/java/ui/components/Workspaces.java
> +        for (WebElement e : boards) {
переделано

2021-11-17 13:14 UTC, elza-99 commented on src/main/java/ui/components/Workspaces.java
> +        driver.manage().timeouts().implicitlyWait(40, TimeUnit.SECONDS);
вынесено в проперти

2021-11-17 13:15 UTC, elza-99 commented on src/main/java/ui/pageobjects/BoardsPage.java
> +    public void addNewList() {
переведено

2021-11-17 13:16 UTC, elza-99 commented on src/main/java/ui/pageobjects/HomePage.java
> +        this.headerMenu = new HeaderMenu(driver);
удалено

2021-11-19 10:05 UTC, merged